### PR TITLE
Tidying css rules

### PR DESCRIPTION
**Pull request by Putti**
This is a suggestion, don't merge yet!

At the moment all the translator*.html files have their own styles defined inside html files. Therefore there is lots of duplication in css rules, and I think that one common css file for all the html files would be great. The styles which don't apply to all html files can be then added to separate css files and linked correspondingly. What do you think?

### CODE REVIEW

**Comment by xpheres** [comment]
Hi, yes, I want to get all the css code out of the html files, I just didn't have much time to work on it. I think it's a great idea!

**Comment by Putti** [comment]
Good to hear that. Now when I started working on this I noticed that there is also lots of rules which don't apply because bootstrap overrides them. Would deleting these rules be okay or is there plans to move fully to non-bootstrap implementation?

**Comment by xpheres** [comment]
I like bootstrap and it helped me much to tidy up the frontend, I don't have any plans to move to a non-bootstrap frontend, however just a few elements depend on bootstrap (hidden menus and rotating messages) so in case I have to change it won't be hard.

**Comment by Putti** [comment]
@xpheres, I have moved all the common css now to style.css and added for translatorocr.html its own ocr.css file in the assets folder. If everything looks good feel free to merge the changes!

**Pull request merged**
